Update aws.yml

diff --git a/.github/workflows/aws.yml b/.github/workflows/aws.yml
--- a/.github/workflows/aws.yml
+++ b/.github/workflows/aws.yml
@@ -16,27 +16,35 @@ jobs:
 
       - name: Modified files
         run: |
-          if [ "${{ github.event_name }}" = "push" ]; then
-            firstCommit="${{ github.event.before }}"
-            lastCommit="${{ github.event.after }}"
-          elif [ "${{ github.event_name }}" = "pull_request" ]; then
+          if [ "${{ github.event.pull_request.merged }}" = "true" ]; then
             firstCommit="${{ github.event.pull_request.base.sha }}"
             lastCommit="${{ github.event.pull_request.head.sha }}"
-          fi
-      
-          echo "First Commit: $firstCommit"
-          echo "Last Commit: $lastCommit"
-      
-          if [ -z "$firstCommit" ] || [ -z "$lastCommit" ]; then
-            echo "Error: firstCommit or lastCommit is empty."
-            exit 1
-          fi
-      
-          changedFiles=$(git diff --name-only --diff-filter=d "$firstCommit" "$lastCommit")
-          echo "Changed files:"
-          echo "$changedFiles"
-          if echo "$changedFiles" | grep -q "aws.yml"; then
-          echo "The file 'aws.yml' has been modified."
+                 
+            echo "First Commit: $firstCommit"
+            echo "Last Commit: $lastCommit"
+        
+            if [ -z "$firstCommit" ] || [ -z "$lastCommit" ]; then
+              echo "Error: firstCommit or lastCommit is empty."
+              exit 1
+            fi
+        
+            changedFiles=$(git diff --name-only --diff-filter=d "$firstCommit" "$lastCommit")
+            echo "Changed files:"
+            echo "$changedFiles"
+            if echo "$changedFiles" | grep -q "aws.yml"; then
+              echo "ts-only=true" >> $GITHUB_ENV
+            else
+              echo "ts-only=false" >> $GITHUB_ENV
+            fi
           else
-            echo "The file 'aws.yml' has not been modified."
-          fi
+            echo "ts-only=false" >> $GITHUB_ENV
+          fi  
+          
+  print: 
+    needs: get_files
+    if: ${{ github.event.pull_request.merged == true && !contains(github.event.pull_request.labels.*.name, 'Version bump') }}
+    runs-on: ubuntu-latest
+    steps:
+      - name: print
+        run: |
+          echo "${{ env.ts-only }}"
