Update aws.yml

diff --git a/.github/workflows/aws.yml b/.github/workflows/aws.yml
--- a/.github/workflows/aws.yml
+++ b/.github/workflows/aws.yml
@@ -16,16 +16,22 @@ jobs:
 
       - name: Modified files
         run: |
-          case '${{ github.event_name }}' in
-            push)
-              firstCommit='${{ github.event.commits[0].id }}'
-              lastCommit='${{ github.event.commits[-1].id }}'
-              ;;
-            pull_request)
-              firstCommit='${{ github.event.base_ref }}'
-              lastCommit='${{ github.event.head_ref }}'
-              ;;
-          esac
-          changedFiles=$(git diff --name-only --diff-filter=d "${firstCommit}~1" "${lastCommit}")
+          if [ "${{ github.event_name }}" = "push" ]; then
+            firstCommit="${{ github.event.before }}"
+            lastCommit="${{ github.event.after }}"
+          elif [ "${{ github.event_name }}" = "pull_request" ]; then
+            firstCommit="${{ github.event.pull_request.base.sha }}"
+            lastCommit="${{ github.event.pull_request.head.sha }}"
+          fi
+      
+          echo "First Commit: $firstCommit"
+          echo "Last Commit: $lastCommit"
+      
+          if [ -z "$firstCommit" ] || [ -z "$lastCommit" ]; then
+            echo "Error: firstCommit or lastCommit is empty."
+            exit 1
+          fi
+      
+          changedFiles=$(git diff --name-only --diff-filter=d "$firstCommit" "$lastCommit")
           echo "Changed files:"
           echo "$changedFiles"
